### ISSUE TITLE
Array is blank

### ISSUE THREAD

**Issue by votlon** [thayton/casperjs-taleo-job-scraper#2]

**Comment by KvdV49** [comment]
Solved, see patch1

**Comment by votlon** [comment]
processPage is not dumping for me, casperjs 1.1.3/phantomjs 1.9.7/nodejs 4.2.6
I'm running it off the command line with `root@superdank:~$ casperjs scraper.js`

This is when running both, master + patch 1

**Comment by votlon** [comment]
patch1 fork does work! 

Since l3com.taeleo.net is forcing https with their website, 
I needed to use,
`root@superdank:~$ casperjs --ignore-ssl-errors=true --ssl-protocol=any scraper.js`
